//app/layout.tsx
import type { Metadata } from "next";
import { AuthProvider } from "@/contexts/auth-context";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {" "}
        <AuthProvider
          fallback={
            <div style={{ padding: 24, backgroundColor: "blue" }}>
              Chargement…
            </div>
          }
        >
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
